version: '2.1'

services:
  app:
    depends_on:
      localstack:
        condition: service_healthy
    build: .
    environment:
    - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
    - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

  localstack:
    image: localstack/localstack
    ports:
    - "4567-4584:4567-4584"
    - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4572"]
      interval: 20s
      timeout: 5s
      retries: 2
